apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        redis-sentinel: "true"
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: registry.peter.com.key
      containers:
      - name: redis-sentinel
        image: sz33sitqdb00ap0007.bf.cn/public/alpine-redis:v3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26379
          name: redis-sentinel
        env:
          - name: SENTINEL
            value: "true"
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: devops-redis-secret
                key: redisAuthPass
