apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
type: "kubernetes.io/rbd"  
data:
  key: QVFBdm5qNWEwVjdtRkJBQW1PUGY0UHBUU3VrcmtIYmNCNGtoaUE9PQ==
  
  #
  #ceph auth get-key client.admin|base64
  #QVFBdm5qNWEwVjdtRkJBQW1PUGY0UHBUU3VrcmtIYmNCNGtoaUE9PQ==

  #
  #