# RABBITMQ_ERLANG_COOKIE= DcvXTukrjUeAl3yzUKUFDtWaQikqTYHV
# RabbitDefaultPass=W43m47nKXEWB
# echo -n "DcvXTukrjUeAl3yzUKUFDtWaQikqTYHV" | base64

# echo -n "W43m47nKXEWB" | base64

apiVersion: v1
kind: Secret
metadata:
  name: default-rabbitmq-secret
  namespace: default
type: Opaque
data:
  rabbitmqErlangCookie: RGN2WFR1a3JqVWVBbDN5elVLVUZEdFdhUWlrcVRZSFY=
  rabbitDefaultPass: VzQzbTQ3bktYRVdC