apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx-load-balancer-conf
  labels:
    app: nginx-ingress-lb
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  body-size: "512m"
  server-name-hash-bucket-size: "256"
  use-proxy-protocol: "true"
